"""
Alembic migration script template.

Revision ID: 0b79e3ca1eff
Revises: allow_guest_conversations
Create Date: 2025-12-14 18:58:50.295863+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b79e3ca1eff'
down_revision = 'allow_guest_conversations'  # Fixed: chain after guest support
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
